---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: db-ejemplo
spec:
  id: db-ejemplo
  compositionSelector:
    matchLabels:
      type: db-aws
      location: local
  parameters:
    db:
      version: "23"
      size: large
